services:
  - type: web
    name: backend
    env: docker
    repo: https://github.com/ashishrathod9/project-desk
    branch: master
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        sync: false
