export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE";

export const FETCH_COMMENTS_BY_ISSUE_REQUEST = "FETCH_COMMENTS_BY_ISSUE_REQUEST";
export const FETCH_COMMENTS_BY_ISSUE_SUCCESS = "FETCH_COMMENTS_BY_ISSUE_SUCCESS";
export const FETCH_COMMENTS_BY_ISSUE_FAILURE = "FETCH_COMMENTS_BY_ISSUE_FAILURE";
